name: Build APK

on:
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Source
    uses: actions/checkout@v4

  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17

  - name: Setup Flutter
    uses: subosito/flutter-action@v2
    with:
      flutter-version: "3.13.9"

  - name: Flutter Pub Get
    run: flutter pub get

  - name: Build APK
    run: flutter build apk --release -v

  - name: Show Build Outputs
    run: |
      echo "===== APK FILES ====="
      find build -name "*.apk" || true

      echo "===== OUTPUTS ====="
      ls -R build/app/outputs || true

  - name: Upload APK
    uses: actions/upload-artifact@v4
    with:
      name: app-release
      path: |
        build/app/outputs/flutter-apk/*.apk
        build/app/outputs/apk/release/*.apk
```
